import 'package:flutter/material.dart';
import 'package:pet_owner_mobile/theme/app_colors.dart';
import 'package:pet_owner_mobile/widgets/custom_back_button.dart';

class TermsConditionsScreen extends StatelessWidget {
  const TermsConditionsScreen({super.key});

  @override
  Widget build(BuildContext context) {
    final sw = MediaQuery.of(context).size.width;
    final sh = MediaQuery.of(context).size.height;

    return Scaffold(
      backgroundColor: Colors.white,
      appBar: AppBar(
        backgroundColor: Colors.white,
        elevation: 0,
        leading: const CustomBackButton(),
        title: Text(
          'Terms & Conditions',
          style: TextStyle(
            fontSize: sw * 0.05,
            fontWeight: FontWeight.bold,
            color: Colors.black87,
          ),
        ),
        centerTitle: true,
      ),
      body: SingleChildScrollView(
        padding: EdgeInsets.symmetric(horizontal: sw * 0.05),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            SizedBox(height: sh * 0.02),

            // Header Banner
            Container(
              width: double.infinity,
              padding: EdgeInsets.all(sw * 0.05),
              decoration: BoxDecoration(
                gradient: LinearGradient(
                  colors: [
                    AppColors.mainColor.withOpacity(0.5),
                    AppColors.darkPink.withOpacity(0.35),
                  ],
                  begin: Alignment.topLeft,
                  end: Alignment.bottomRight,
                ),
                borderRadius: BorderRadius.circular(sw * 0.04),
              ),
              child: Row(
                children: [
                  Container(
                    padding: EdgeInsets.all(sw * 0.03),
                    decoration: BoxDecoration(
                      color: Colors.white,
                      borderRadius: BorderRadius.circular(sw * 0.03),
                    ),
                    child: Icon(
                      Icons.description_outlined,
                      color: AppColors.darkPink,
                      size: sw * 0.08,
                    ),
                  ),
                  SizedBox(width: sw * 0.04),
                  Expanded(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text(
                          'Terms of Service',
                          style: TextStyle(
                            fontSize: sw * 0.042,
                            fontWeight: FontWeight.bold,
                            color: Colors.black87,
                          ),
                        ),
                        SizedBox(height: sh * 0.005),
                        Text(
                          'Last updated: January 2025',
                          style: TextStyle(
                            fontSize: sw * 0.032,
                            color: Colors.black54,
                          ),
                        ),
                      ],
                    ),
                  ),
                ],
              ),
            ),

            SizedBox(height: sh * 0.025),

            _TermsSection(
              sw: sw,
              sh: sh,
              number: '1',
              title: 'Acceptance of Terms',
              body:
                  'By downloading, installing, or using the PetCare application, you agree to be bound by these Terms and Conditions. If you do not agree with any part of these terms, you may not use our services.',
            ),
            _TermsSection(
              sw: sw,
              sh: sh,
              number: '2',
              title: 'Use of the App',
              body:
                  'PetCare is intended for personal, non-commercial use. You agree to use the app only for lawful purposes and in a manner that does not infringe the rights of others. You are responsible for maintaining the confidentiality of your account credentials.',
            ),
            _TermsSection(
              sw: sw,
              sh: sh,
              number: '3',
              title: 'Pet Management',
              body:
                  'You are solely responsible for the accuracy of your pet\'s information entered into the app. PetCare provides tools to help you manage your pets but is not a substitute for professional veterinary advice or care.',
            ),
            _TermsSection(
              sw: sw,
              sh: sh,
              number: '4',
              title: 'AI Nutrition Plans',
              body:
                  'Nutrition plans generated by our AI are intended as general guidance only. They are based on the information you provide and should not replace advice from a qualified veterinarian or animal nutritionist. Always consult a professional for specific health concerns.',
            ),
            _TermsSection(
              sw: sw,
              sh: sh,
              number: '5',
              title: 'Vet Bookings',
              body:
                  'PetCare facilitates appointment bookings between pet owners and veterinary providers. We are not responsible for the quality, safety, or outcome of veterinary services. Cancellation and refund policies are governed by the individual vet clinic.',
            ),
            _TermsSection(
              sw: sw,
              sh: sh,
              number: '6',
              title: 'E-Commerce & Purchases',
              body:
                  'All product purchases made through the PetCare shop are subject to our returns and refunds policy. Prices and availability are subject to change without notice. We reserve the right to cancel orders at our discretion.',
            ),
            _TermsSection(
              sw: sw,
              sh: sh,
              number: '7',
              title: 'Pet Adoption',
              body:
                  'The adoption feature connects prospective pet owners with shelters and individuals. PetCare does not guarantee the health, temperament, or legal ownership status of any listed animal. Users are advised to conduct their own due diligence.',
            ),
            _TermsSection(
              sw: sw,
              sh: sh,
              number: '8',
              title: 'Intellectual Property',
              body:
                  'All content within the PetCare app, including but not limited to text, graphics, logos, and software, is the property of PetCare and is protected by applicable intellectual property laws. You may not reproduce or distribute any content without prior written permission.',
            ),
            _TermsSection(
              sw: sw,
              sh: sh,
              number: '9',
              title: 'Limitation of Liability',
              body:
                  'PetCare shall not be liable for any indirect, incidental, or consequential damages arising from the use or inability to use our services. Our total liability to you for any claim shall not exceed the amount paid by you to PetCare in the past twelve months.',
            ),
            _TermsSection(
              sw: sw,
              sh: sh,
              number: '10',
              title: 'Changes to Terms',
              body:
                  'We reserve the right to update these Terms and Conditions at any time. Continued use of the app after changes are posted constitutes your acceptance of the revised terms. We will notify you of significant changes via the app or email.',
            ),

            SizedBox(height: sh * 0.015),

            // Contact Note
            Container(
              width: double.infinity,
              padding: EdgeInsets.all(sw * 0.04),
              decoration: BoxDecoration(
                color: AppColors.mainColor.withOpacity(0.18),
                borderRadius: BorderRadius.circular(sw * 0.03),
                border: Border.all(color: AppColors.mainColor.withOpacity(0.5)),
              ),
              child: Row(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Icon(
                    Icons.info_outline,
                    color: AppColors.darkPink,
                    size: sw * 0.05,
                  ),
                  SizedBox(width: sw * 0.03),
                  Expanded(
                    child: Text(
                      'For any questions about these terms, please contact us at legal@petcare.com',
                      style: TextStyle(
                        fontSize: sw * 0.034,
                        color: Colors.black54,
                        height: 1.5,
                      ),
                    ),
                  ),
                ],
              ),
            ),

            SizedBox(height: sh * 0.04),
          ],
        ),
      ),
    );
  }
}

class _TermsSection extends StatelessWidget {
  final double sw;
  final double sh;
  final String number;
  final String title;
  final String body;

  const _TermsSection({
    required this.sw,
    required this.sh,
    required this.number,
    required this.title,
    required this.body,
  });

  @override
  Widget build(BuildContext context) {
    return Container(
      margin: EdgeInsets.only(bottom: sh * 0.015),
      padding: EdgeInsets.all(sw * 0.04),
      decoration: BoxDecoration(
        color: AppColors.lightGray,
        borderRadius: BorderRadius.circular(sw * 0.03),
      ),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Container(
            width: sw * 0.08,
            height: sw * 0.08,
            decoration: BoxDecoration(
              color: AppColors.darkPink.withOpacity(0.12),
              shape: BoxShape.circle,
            ),
            alignment: Alignment.center,
            child: Text(
              number,
              style: TextStyle(
                fontSize: sw * 0.035,
                fontWeight: FontWeight.bold,
                color: AppColors.darkPink,
              ),
            ),
          ),
          SizedBox(width: sw * 0.035),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  title,
                  style: TextStyle(
                    fontSize: sw * 0.038,
                    fontWeight: FontWeight.bold,
                    color: Colors.black87,
                  ),
                ),
                SizedBox(height: sh * 0.007),
                Text(
                  body,
                  style: TextStyle(
                    fontSize: sw * 0.033,
                    color: Colors.black54,
                    height: 1.6,
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}
